remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

title: Documentación

nombres: Juan Manuel Isaza Quiceno
submodulo: Introducción a la Programación
periodo: 2023-2
url_foto: https://firebasestorage.googleapis.com/v0/b/adivina-b2f41.appspot.com/o/imagen_2023-10-18_205737992.png?alt=media&token=8f6321cf-bfb0-4de4-b354-e53e8be55f4e&_gl=1*dv235p*_ga*Mjg5MTMwODkyLjE2OTc2ODA1NjE.*_ga_CW55HF8NVT*MTY5NzY4MDU2MS4xLjEuMTY5NzY4MDY2Ni41MC4wLjA

